name: Issues Reporter
on: issues
jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Print output
        run: |
            echo "Event ID: ${{ github.event.issue.id }}"
            echo "Author: ${{ github.event.issue.author_association }}"
            echo "Title: ${{ github.event.issue.title }}"
            echo "Body: ${{ github.event.issue.body }}"
  full_output:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Print full output
        run: echo "${{ toJSON(github.event) }}"